[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuild = false
    skipInstall = false

[functions]
  included_files = ["src/app/**/*"] 